import io
from bs4 import BeautifulSoup
import requests
from PIL import Image
import PySimpleGUI as sg
import time

# example photo popup (similar to yours without all the detail)
def picsPopup(title, picsA):
    layout = []
    row = []
    for pic in picsA:
        row.append(sg.Image(pic))
    layout.append(row)

    sg.Window(title, layout, keep_on_top=True,modal=True).read(close=2000)

# converts jpg to png byte data
def convert_jpg(img_urls):

    # holds converted data
    png_array = []

    for image in img_urls:
        image = image.strip('\n')
        img_data = requests.get(image).content
        pil_image = Image.open(io.BytesIO(img_data))
        png_bio = io.BytesIO()
        pil_image.save(png_bio, format="PNG")
        png_data = png_bio.getvalue()
        png_array.append(png_data)

    return png_array

# PySimpleGUI stuff
layout = [
    [sg.Button("Display Images")]
]

window = sg.Window("Testing", layout)
while True:
    event, values = window.read()
    if event == "EXIT" or event == sg.WIN_CLOSED:
        break
    if event == "Display Images":
        # write desired player page url to the player_url file
        with open("player_url.txt", "w") as file:
            file.write("https://www.baseball-reference.com/players/a/abreual01.shtml") # this would be generated by whichever player is clicked

        # might be necessary (unsure)
        time.sleep(1)

        # holds response
        img_urls = []
        # check for response in player_url.txt file
        with open("player_images.txt", "r") as file:
            for line in file:
                img_urls.append(line)

        # error checking
        if img_urls[0] == "No Images Found":
            # do something
            break
        elif img_urls[0] == "ERROR: Invalid URL":
            # do something
            break
        else:
            png_imgs = convert_jpg(img_urls)
            picsPopup("images of player", png_imgs)

window.close()

